API calls refactored
Gibo-Will02/annotations-api pull request #7
Opened 2024-01-31 19:16 UTC by nlillich

2024-01-31 19:17 UTC, DarkerYetDarker approved these changes
I Approve

2024-01-31 19:19 UTC, NathanHerscovici approved these changes
Looks good to me

2024-01-31 19:20 UTC, Gibo-Will02 requested changes
Look at modifying line 8 in server/src/app.js as to not be a long list of {...}

2024-02-03 20:33 UTC, Gibo-Will02 approved these changes
LGTM

2024-02-03 20:44 UTC, merged